
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lemon?serverTimezone=Asia/Shanghai&useunicode=true&characterEncoding=utf8&useSSL=false
    password: root
    username: root
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

